language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
notifications:
  email: false
env: 
  - CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++-4.9
    - make