version: '3.3'
services:
  website:
    build: .
    ports:
      - "8080:8080"
    container_name: rag
    depends_on:
      - "database"
    volumes:
      - "./frontend/src:/usr/src/ragsite/frontend/src"
      - "./server/src:/usr/src/ragsite/server/src"
  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: rag
      MYSQL_USER: rag
      MYSQL_PASSWORD: rag
