// flow-typed signature: f892382f51023052f09d34199c8c8a6c
// flow-typed version: <<STUB>>/containerized_v^1.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'containerized'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'containerized' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'containerized/lib/cmd' {
  declare module.exports: any;
}

declare module 'containerized/lib/hostname' {
  declare module.exports: any;
}

declare module 'containerized/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'containerized/index' {
  declare module.exports: $Exports<'containerized'>;
}
declare module 'containerized/index.js' {
  declare module.exports: $Exports<'containerized'>;
}
declare module 'containerized/lib/cmd.js' {
  declare module.exports: $Exports<'containerized/lib/cmd'>;
}
declare module 'containerized/lib/hostname.js' {
  declare module.exports: $Exports<'containerized/lib/hostname'>;
}
declare module 'containerized/test/index.js' {
  declare module.exports: $Exports<'containerized/test/index'>;
}
