// flow-typed signature: ccad09ed4a8a6314b943f34dedefe43a
// flow-typed version: <<STUB>>/passport-json_v^1.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-json/src/index' {
  declare module.exports: any;
}

declare module 'passport-json/src/strategy' {
  declare module.exports: any;
}

declare module 'passport-json/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-json/index' {
  declare module.exports: $Exports<'passport-json'>;
}
declare module 'passport-json/index.js' {
  declare module.exports: $Exports<'passport-json'>;
}
declare module 'passport-json/src/index.js' {
  declare module.exports: $Exports<'passport-json/src/index'>;
}
declare module 'passport-json/src/strategy.js' {
  declare module.exports: $Exports<'passport-json/src/strategy'>;
}
declare module 'passport-json/src/utils.js' {
  declare module.exports: $Exports<'passport-json/src/utils'>;
}
