// flow-typed signature: 080d6ad61999b68d33dfc9251d16143a
// flow-typed version: <<STUB>>/slate-html-serializer_v^0.5.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-html-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-html-serializer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-html-serializer/dist/slate-html-serializer' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/dist/slate-html-serializer.min' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/lib/slate-html-serializer.es' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/lib/slate-html-serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-html-serializer/dist/slate-html-serializer.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer'>;
}
declare module 'slate-html-serializer/dist/slate-html-serializer.min.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer.min'>;
}
declare module 'slate-html-serializer/lib/slate-html-serializer.es.js' {
  declare module.exports: $Exports<'slate-html-serializer/lib/slate-html-serializer.es'>;
}
declare module 'slate-html-serializer/lib/slate-html-serializer.js' {
  declare module.exports: $Exports<'slate-html-serializer/lib/slate-html-serializer'>;
}
