// flow-typed signature: 09cd0a5ed39b6c99d152f128a5b37078
// flow-typed version: <<STUB>>/slate-drop-or-paste-images_v^0.8.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-drop-or-paste-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-drop-or-paste-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-drop-or-paste-images/dist/slate-drop-or-paste-images' {
  declare module.exports: any;
}

declare module 'slate-drop-or-paste-images/dist/slate-drop-or-paste-images.min' {
  declare module.exports: any;
}

declare module 'slate-drop-or-paste-images/lib/data-uri-to-blob' {
  declare module.exports: any;
}

declare module 'slate-drop-or-paste-images/lib/image-to-data-uri' {
  declare module.exports: any;
}

declare module 'slate-drop-or-paste-images/lib/index' {
  declare module.exports: any;
}

declare module 'slate-drop-or-paste-images/lib/load-image-file' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-drop-or-paste-images/dist/slate-drop-or-paste-images.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/dist/slate-drop-or-paste-images'>;
}
declare module 'slate-drop-or-paste-images/dist/slate-drop-or-paste-images.min.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/dist/slate-drop-or-paste-images.min'>;
}
declare module 'slate-drop-or-paste-images/lib/data-uri-to-blob.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/lib/data-uri-to-blob'>;
}
declare module 'slate-drop-or-paste-images/lib/image-to-data-uri.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/lib/image-to-data-uri'>;
}
declare module 'slate-drop-or-paste-images/lib/index.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/lib/index'>;
}
declare module 'slate-drop-or-paste-images/lib/load-image-file.js' {
  declare module.exports: $Exports<'slate-drop-or-paste-images/lib/load-image-file'>;
}
